version: '3.1'

services:
  db:
    image: postgres:alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
  fakeapi:
    build: ./CryptoApi
    container_name: api
    restart: always
    ports:
      - "80:80"
    